name: Build and deploy Python app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Create a temporary directory for packaging
        run: mkdir temp

      - name: Copy files to temporary directory, excluding temp and venv
        run: |
          rsync -av --exclude 'venv/' --exclude '__pycache__/' ./ temp/

      - name: Create tar artifact for deployment
        run: |
          tar -czf release.tar.gz -C temp .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.tar.gz  # Cambiado a tar.gz

  # Remove the deploy job as it is specific to Azure
